[project]
name = "sdotml"
version = "0.1.0"
description = "Image classification: AI-generated vs human-created"
license = { text = "MIT" }
readme = "README.md"
authors = [
    { name = "Unai Lalana" },
    { name = "Eneko Isturitz" }
]
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.49.1",
    "matplotlib>=3.10.6",
    "opencv-contrib-python>=4.12.0.88",
    "opencv-python>=4.12.0.88",
    "pandas>=2.3.2",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
]

[dependency-groups]
dev = [
    "pdoc3>=0.11.6",
]
